name: Docker Image CI

on:
  push:
    branches: [ lwm ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER_LWM}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD_LWM}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t luxury-world-madrid --build-arg ENVIRONMENT=prod-lwm --build-arg SOURCE_COMMIT=${{steps.vars.outputs.sha_short}}
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER_LWM}}/luxury-world-madrid:latest
